version: "3.9"

networks:
  summafy-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: emma
      POSTGRES_PASSWORD: happy
      POSTGRES_DB: summafy
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - summafy-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://emma:happy@postgres:5432/summafy?sslmode=disable"
    networks:
      - summafy-network

volumes:
  postgres-data: