// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: activities.sql

package db

import (
	"context"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
  activity
 ) VALUES (
  $1
) RETURNING id, username, activity, created_at, document_id
`

func (q *Queries) CreateActivity(ctx context.Context, activity int64) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity, activity)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Activity,
		&i.CreatedAt,
		&i.DocumentID,
	)
	return i, err
}

const getAllActivitiesForUser = `-- name: GetAllActivitiesForUser :many
SELECT id, username, activity, created_at, document_id FROM activities
WHERE user = $1
`

func (q *Queries) GetAllActivitiesForUser(ctx context.Context, dollar_1 interface{}) ([]Activity, error) {
	rows, err := q.db.Query(ctx, getAllActivitiesForUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Activity,
			&i.CreatedAt,
			&i.DocumentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastActivityForUser = `-- name: GetLastActivityForUser :one
SELECT id, username, activity, created_at, document_id FROM activities
WHERE user = $1 AND id = (SELECT MAX(id) FROM activities WHERE user = $1) LIMIT 1
`

func (q *Queries) GetLastActivityForUser(ctx context.Context, dollar_1 interface{}) (Activity, error) {
	row := q.db.QueryRow(ctx, getLastActivityForUser, dollar_1)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Activity,
		&i.CreatedAt,
		&i.DocumentID,
	)
	return i, err
}
