name: Deploy to production

'on':
  push:
    branches:
      - main

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set Production mode and AWS config
      run: |
        echo "PROD=true" >> app.env
    
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v3
       with:
        role-to-assume: arn:aws:iam::120569638976:role/GitHubActionsRole_summafyapp
        aws-region: us-east=1
       
    # - name: Replace placeholders in app.env
    #   run: |
    #     sed -i '/DB_URL/d' app.env
    #     sed -i '/DB_DRIVER/d' app.env
    #     echo "DB_URL=${{ vars.DATABASE_URL }}" >> app.env
    #     echo "DB_DRIVER=${{ vars.DATABASE_DRIVER }}" >> app.env
    #     echo "TODO change API_KEY, PORT and SERVER_ADDRESS"
    #     cat app.env
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: summafy-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
      
      #   - name: Build and push Docker image
      # uses: docker/build-push-action@v3
      # run: |
      #   docker build -t summafy-repo .
      #   docker tag summafy-repo:latest 120569638976.dkr.ecr.us-east-1.amazonaws.com/summafy-repo:latest
      #   docker push 120569638976.dkr.ecr.us-east-1.amazonaws.com/summafy-repo:latest