name: Unit Tests

'on':
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: 
      name: ci
    env:
      MODE: test
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: test123
          POSTGRES_DB: summafy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.22.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install goose
      run: |
        go install github.com/pressly/goose/v3/cmd/goose@latest
        which goose

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: go test -v -cover -short ./...

